const array = [
  {
    name: "kamen rider ex-aid",
    time: "heisei",
    episodes: "45",
    picture: "picture/ex aid.png",
    year: "2016-2017",
  },
  {
    name: "kamen rider build",
    time: "heisei",
    episodes: "49",
    picture: "picture/Build_Poster.png",
    year: "2017-2018",
  },
  {
    name: "ultraman dyna",
    time: "heisei",
    episodes: "51",
    picture: "picture/dyna.png",
    year: "1997-1998",
  },
  {
    name: "Dekaranger",
    time: "heisei",
    episodes: "49",
    picture: "picture/dekaranger.png",
    year: "2004-2005",
  },
  {
    name: "Shinkenger",
    time: "heisei",
    episodes: "49",
    picture: "picture/shinkenger.jpg",
    year: "2009-2010",
  },
  {
    name: "ultraman orb",
    time: "heisei",
    episodes: "25",
    picture: "picture/orb.jpg",
    year: "2016",
  },
  {
    name: "kamen rider W",
    time: "heisei",
    episodes: "49",
    picture: "picture/W.jpg",
    year: "2009-2010",
  },
  {
    name: "kamen rider zero-one",
    time: "reiwa",
    episodes: "45",
    picture: "picture/Zero one.png",
    year: "2019-2020",
  },
  {
    name: "kamen rider revice",
    time: "reiwa",
    episodes: "50",
    picture: "picture/revice.png",
    year: "2021-2022",
    desc: "In 1971, a scientific expedition in Latin America had uncovered an ancient artifact containing the remains of the demon Giff, leading to the creation of the Vistamps. In the present day, the remains of Giff now lie in the hands of a demon cult called the Deadmans, who seek to resurrect him by converting peoples' inner demons into their fold. Fenix, a governmental organization opposing the Deadmans, have developed the Revice Driver for someone with complete control over their inner demon. Ikki Igarashi, a young man who runs a public bath with his family, comes into acquisition of the belt while forming a contract with his inner demon Vice. Together, as Kamen Rider Revi and Vice, they are Kamen Rider Revice!",
  },
  {
    name: "ultraman decker",
    time: "reiwa",
    episodes: "25",
    picture: "picture/Decker.png",
    year: "2022-2023",
  },
  {
    name: "ultraman taiga",
    time: "reiwa",
    episodes: "26",
    picture: "picture/taiga.png",
    year: "2019-2019",
  },
  {
    name: "donbrothers",
    time: "reiwa",
    episodes: "50",
    picture: "picture/donbros.png",
    year: "2022-2023",
  },
  {
    name: "zenkaiger",
    time: "reiwa",
    episodes: "49",
    picture: "picture/kikai.jpg",
    year: "2021-2022",
  },
];
export { array };
